config/routes.rb
Rails.application.routes.draw do
devise_for :users
root "homes#index"
resources :exportnews
resources :photos
resources :homes
resources :vegetables
resources :profiles
resources :news
resources :exportleads
resources :connect_buyers
get '/trade_news' => 'exportleads#trade_news'
get '/export_leads' => 'exportleads#export_leads'
get '/home_password_974000' => 'homes#home_password_974000'
get '/about_us' => 'homes#about_us'
get '/privacy_policy' =>'homes#privacy_policy'  
get '/terms_and_condition' =>'homes#terms_and_condition'   
get '/barley' => 'homes#barley'
get '/buckwheat' =>'homes#buckwheat'    
get '/barley' => 'homes#barley'
get '/buckwheat' =>'homes#buckwheat'
get '/canary_seed' =>'homes#canary_seed'
get '/cotton' =>'homes#cotton'
get '/fonio' =>'homes#fonio'
get '/maize' =>'homes#maize'
get '/millet_crop' =>'homes#millet_crop'
get '/oats' => 'homes#oats'
get '/quinoa' => 'homes#quinoa'
get'/rice' => 'homes#rice'
get'/rye' => 'homes#rye'
get'/sorghum' => 'homes#sorghum'
get'/triticale' => 'homes#triticale'
get'/wheat' => 'homes#wheat'
get'/bitter_gourd' => 'vegetables#bitter_gourd'
get'/broccoli' => 'vegetables#broccoli'
get'/cabbages' => 'vegetables#cabbages'
get'/capsicums' => 'vegetables#capsicums'
get'/carrots' => 'vegetables#carrots'
get'/cassava' => 'vegetables#cassava'
get'/cauliflower' => 'vegetables#cauliflower'
get'/chickpea' => 'vegetables#chickpea'
get'/chicory' => 'vegetables#chicory'
get'/cucumber' => 'vegetables#cucumber'
get'/drumstick' => 'vegetables#drumstick'
get'/dry_bean' => 'vegetables#dry_bean'
get'/eggplant' => 'vegetables#eggplant'
get'/ginger' => 'vegetables#ginger'
get'/green_bean' => 'vegetables#green_bean'
get'/green_peas' => 'vegetables#green_peas'
get'/ladys_finger' => 'vegetables#ladys_finger'
get'/lentil' => 'vegetables#lentil'
get'/lettuce' => 'vegetables#lettuce'
get'/mushroom' => 'vegetables#mushroom'
get'/okra' => 'vegetables#okra'
get'/onion' => 'vegetables#onion'
get'/potato' => 'vegetables#potato'
get'/pulses' => 'vegetables#pulses'
get'/pumpkin_squash_gourd' => 'vegetables#pumpkin_squash_gourd'
get'/radish' => 'vegetables#radish'
get'/rapeseed_canola' => 'vegetables#rapeseed_canola'
get'/ridge_Gourd' => 'vegetables#ridge_Gourd'
get'/sunflower' => 'vegetables#sunflower'
get'/sesame' => 'vegetables#sesame'
get'/soybean' => 'vegetables#soybean'
get'/spinach' => 'vegetables#spinach'
get'/sugar_cane' => 'vegetables#sugar_cane'
get'/sugar_beet_beetroot' => 'vegetables#sugar_beet_beetroot'
get'/sunflower_seed' => 'vegetables#sunflower_seed'
get'/sanflower' => 'vegetables#sanflower'
get'/tomato' => 'vegetables#tomato'
get'/turnip' => 'vegetables#turnip'
get'/yams' =>'vegetables#yams' 
get '/apple' =>'fruits#apple'
get '/apricot' =>'fruits#apricot'
get '/avocado' =>'fruits#avocado'
get '/banana' =>'fruits#banana'
get '/black_currant' =>'fruits#black_currant'
get '/blackberry' =>'fruits#blackberry'
get '/blueberry' =>'fruits#blueberry'
get '/cherry' =>'fruits#cherry'
get '/coconut' =>'fruits#coconut'
get '/currant' =>'fruits#currant'
get '/custard_apple' =>'fruits#custard_apple'
get '/date' =>'fruits#date'
get '/dragon_fruit' =>'fruits#dragon_fruit'
get '/fig' =>'fruits#fig'
get '/gooseberry' =>'fruits#gooseberry'
get '/grape' =>'fruits#grape'
get '/guava' =>'fruits#guava'
get '/jackfruit' =>'fruits#jackfruit'
get '/kiwifruit' =>'fruits#kiwifruit'
get '/lemons' =>'fruits#lemons'
get '/mango' =>'fruits#mango'
get '/mangosteen' =>'fruits#mangosteen'
get '/muskmelon' =>'fruits#muskmelon'
get '/olive' =>'fruits#olive'
get '/oranges' =>'fruits#oranges'
get '/papaya' =>'fruits#papaya'
get '/passion_fruit' =>'fruits#passion_fruit'
get '/peach' =>'fruits#peach'
get '/pear' =>'fruits#pear'
get '/pineapple' =>'fruits#pineapple'
get '/plums' =>'fruits#plums'
get '/pomegranate' =>'fruits#pomegranate'
get '/quince' =>'fruits#quince'
get '/raspberry' =>'fruits#raspberry'
get '/strawberry' =>'fruits#strawberry'
get '/watermelon' =>'fruits#watermelon'
get '/beef' => 'meats#beef'
get '/buffalo' => 'meats#buffalo'
get '/camel' => 'meats#camel'
get '/chicken' => 'meats#chicken'
get '/duck' => 'meats#duck'
get '/goat' => 'meats#goat'
get '/goose' => 'meats#goose'
get '/guinea' => 'meats#guinea'
get '/horse' => 'meats#horse'
get '/pork' => 'meats#pork'
get '/rabbit' => 'meats#rabbit'
get '/sheep' => 'meats#sheep'
get '/turkey' => 'meats#turkey'

get '/beer' => 'milks#beer'
get '/buffalo_milk' => 'milks#buffalo_milk'
get '/camel_milk' => 'milks#camel_milk'
get '/coffee' => 'milks#coffee'
get '/cow_milk' => 'milks#cow_milk'
get '/goat_milk' => 'milks#goat_milk'
get '/milk' => 'milks#milk'
get '/sheep_milk' => 'milks#sheep_milk'
get '/tea' => 'milks#tea'
get '/wine' => 'milks#wine'
get '/almonds' => 'nuts#almonds'
get '/brazil_nuts' => 'nuts#brazil_nuts'
get '/cashews' => 'nuts#cashews'
get '/chestnuts' => 'nuts#chestnuts'
get '/filberts' => 'nuts#filberts'
get '/hazelnuts' => 'nuts#hazelnuts'
get '/macadamia_nuts' => 'nuts#macadamia_nuts'
get '/peanuts' => 'nuts#peanuts'
get '/pecans' => 'nuts#pecans'
get '/pine_nuts' => 'nuts#pine_nuts'
get '/pistachios' => 'nuts#pistachios'
get '/sheanut' => 'nuts#sheanut'
get '/walnuts' => 'nuts#walnuts'
get '/anise_star' => 'spices#anise_star'
get '/bay_leaves' => 'spices#bay_leaves'
get '/black_pepper' => 'spices#black_pepper'
get '/cardamom' => 'spices#cardamom'
get '/chili_pepper' => 'spices#chili_pepper'
get '/cinnamon' => 'spices#cinnamon'
get '/cloves' => 'spices#cloves'
get '/coriander' => 'spices#coriander'
get '/cumin' => 'spices#cumin'
get '/fennel' => 'spices#fennel'
get '/fenugreek' => 'spices#fenugreek'
get '/ginger' => 'spices#ginger'
get '/mace' => 'spices#mace'
get '/mustard_seeds' => 'spices#mustard_seeds'
get '/nutmeg' => 'spices#nutmeg'
get '/oregano' => 'spices#oregano'
get '/paprika' => 'spices#paprika'
get '/peppermint' => 'spices#peppermint'
get '/rosemary' => 'spices#rosemary'
get '/saffron' => 'spices#saffron'
get '/thyme' => 'spices#thyme'
get '/turmeric' => 'spices#turmeric'
get '/vanilla' => 'spices#vanilla' 

get '/cheese' => 'milks#cheese' 
get '/cocoa' => 'milks#cocoa'	
get '/yerba_mate' => 'milks#yerba_mate'	
get '/egg' => 'milks#egg'
get '/honey' => 'milks#honey'
get '/olive_oil' => 'milks#olive_oil'	 
get '/tobacco' => 'milks#tobacco'	 

get '/fiber' => 'fiber#fiber'
get '/abaca_fiber' => 'fiber#abaca_fiber'	
get '/agave_fiber' => 'fiber#agave_fiber'	
get '/bast_fiber' => 'fiber#bast_fiber'	
get '/flax_fiber' => 'fiber#flax_fiber'	
get '/jute_fiber' => 'fiber#jute_fiber'	
get '/kapok_fiber' => 'fiber#kapok_fiber'		
get '/ramie_fiber' => 'fiber#ramie_fiber'	
get '/rubber_fiber' => 'fiber#rubber_fiber'	
get '/silk_fiber' => 'fiber#silk_fiber'	
get '/sisal_fiber' => 'fiber#sisal_fiber' 

get '/wool' => 'fiber#wool' 

get '/fish' => 'seafoods#fish'
get '/Oyster' => 'seafoods#Oyster'
get '/seaweed' => 'seafoods#seaweed'
get '/caviar' => 'seafoods#caviar'
get '/crab' => 'seafoods#crab'
get '/lobsters' => 'seafoods#lobsters'
get '/clam' => 'seafoods#clam'
get '/oyster' => 'seafoods#oyster'
get '/octopus' => 'seafoods#octopus'
get '/squid' => 'seafoods#squid'
get '/shrimps' => 'seafoods#shrimps'

end

app/models/profile.rb
class Profile < ApplicationRecord
  
    belongs_to :user

    validates_presence_of :product_name, presence:{:message => "Product Name can't be blank"}
    validates_presence_of :company_name, presence:{:message => "Company Name can't be blank"}
    validates_presence_of :about_company, presence:{:message => "About Company can't be blank"}
    
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def index
    @users = User.all
    end

    def new
       @profile = Profile.new
    end

    def show
      @user = User.find(params[:id])
      @profile = Profile.where(params[:id])
      @profiles = Profile.order('created_at DESC')
      @connect_buyer = ConnectBuyer.order('created_at DESC')
    end

    def edit
        @user = User.find(params[:user_id])
        @profile = Profile.find(params[:profile_id])
    end

    def create

        @profile = current_user.profiles.build(profile_params)
          if @profile.save
            redirect_to profile_path(@profile.user.id),notice: "Business Info Added Successfully"
          else
            render "new"
          end
    end

    def update
        @profile = Profile.find(params[:id])
		if  @profile.update(profile_params)
            redirect_to profile_path(@profile.user.id),notice: "Edit Successfully"
        else
            render 'edit'
        end
    end

    def destroy
        @profile = Profile.find(params[:id])
        @profile.destroy
        redirect_to profile_path(@profile.user.id)
    end

    private

    def profile_params
        params.require(:profile).permit(:product_name,:company_name,:minimun_order,:target_country,:about_company)
    end



    #def check_quota
    #    if !@user.profiles.nil? && @user.profiles.count >= 1
    #    end
    #end

end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Eximsquare</title>
<style>
</style>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7201484819730179"
     crossorigin="anonymous"></script>
</head>

<body id="myPage">
<div class="w3-container w3-content" style="max-width:1400px;margin-top:60px"> 
<div class="col-md-7 col-sm-7 col-md-offset-2">
<div class="w3-panel w3-card w3-responsive">
<div class="w3-container w3-margin-bottom">

<h3 class="w3-text-teal">Edit Business Information</h3>

<%= form_for @profile do |f| %>

<%= f.label :product_name,'Business Name'%></br>
<%= f.text_field :product_name,class: "form-control",:maxlength=>"50",placeholder:"Business Name can't be blank"%></br>

<%= f.label :company_name,'Business Name'%></br>
<%= f.text_field :company_name,class: "form-control",:maxlength=>"50",placeholder:"Business Name can't be blank"%></br>

<%= f.label :minimun_order,'Minimum Order'%></br>
<%= f.text_field :minimun_order,class: "form-control",:maxlength=>"40",placeholder:"Minimun Order can't be blank"%></br>

<%= f.label :target_country,'Top three country you Import/Export'%></br>
<%= f.text_field :target_country,class: "form-control",:maxlength=>"60",placeholder:"Country name can't be blank"%></br>

<%= f.label :about_company,'About Business'%></br>
<%= f.text_area :about_company,class: "form-control",:maxlength=>"500",:rows => 4,:cols => 60,placeholder:"About Business Info can't be blank"%></br>

<%= f.submit"Add Business Info",class: "w3-btn w3-teal"%>

<%end%>


</div>
</div>
</div>

</div>


</body>
</html>

app/views/profiles/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Eximsquare</title>
<style>
</style>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7201484819730179"
     crossorigin="anonymous"></script>
</head>

<body id="myPage">
<div class="w3-container w3-content" style="max-width:1400px;margin-top:60px"> 
<div class="col-md-7 col-sm-7 col-md-offset-2">
<div class="w3-panel w3-card w3-responsive">
<div class="w3-container w3-margin-bottom">

<h3>Add Business Information</h3>

<%= form_for @profile do |f| %>

<%= f.label :product_name,'Business Name'%></br>
<%= f.text_field :product_name,class: "form-control",:maxlength=>"50",placeholder:"Business Name can't be blank"%></br>

<%= f.label :company_name,'Business Name'%></br>
<%= f.text_field :company_name,class: "form-control",:maxlength=>"50",placeholder:"Business Name can't be blank"%></br>

<%= f.label :minimun_order,'Minimum Order'%></br>
<%= f.text_field :minimun_order,class: "form-control",:maxlength=>"40",placeholder:"Minimun Order can't be blank"%></br>

<%= f.label :target_country,'Top three country you Import/Export'%></br>
<%= f.text_field :target_country,class: "form-control",:maxlength=>"60",placeholder:"Country name can't be blank"%></br>

<%= f.label :about_company,'About Business'%></br>
<%= f.text_area :about_company,class: "form-control",:maxlength=>"500",:rows => 4,:cols => 60,placeholder:"About Business Info can't be blank"%></br>

<%= f.submit"Add Business Info",class: "w3-btn w3-teal"%>

<%end%>


</div>
</div>
</div>

</div>


</body>
</html>

app/views/profiles/show.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Eximsquare</title>
<style>
.user_profile {
  height: 300px;
  overflow-y: scroll;
}
</style>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7201484819730179"
     crossorigin="anonymous"></script>
</head>
<body id="myPage">
<div class="w3-container w3-content" style="max-width:1400px;margin-top:60px">
<div class="col-md-12 col-sm-12">
<div class="row">

<div class="col-md-3 col-sm-3">
<div class="user_profile w3-panel w3-card w3-responsive">
<h5 class=""><b></b></h5>
</br>
<%if @user.business_type == 'Retail store'%>
<i><%=image_tag "Paper.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Agriculture,Animal,Food & Beverages'%>
<i><%=image_tag "Agriculture.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Apparel, Textile & Leather'%>
<i><%=image_tag "Apparel.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Fashion Accessories & wear'%>
<i><%=image_tag "FashionAccessories.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Cosmetic & Beauty'%>
<i><%=image_tag "Cosmetic.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Sports & Fitness'%>
<i><%=image_tag "Sports.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Automobiles & Transportations'%>
<i><%=image_tag "Automobiles.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Computer & Telecommunication'%>
<i><%=image_tag "Computer.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Electronics'%>
<i><%=image_tag "Electronics.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Electrical'%>
<i><%=image_tag "Electrical.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Education service business'%>
<i><%=image_tag "College.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Buildings & Construction'%>
<i><%=image_tag "Furniture.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'School, College & University'%>
<i><%=image_tag "College.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Hospital & Medical'%>
<i><%=image_tag "Hospital.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Household & Kitchen'%>
<i><%=image_tag "Household.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Hotel/Touism/Paying guest'%>
<i><%=image_tag "Furniture.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Machinery & Industrial parts'%>
<i><%=image_tag "Machinery.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Manufacturer'%>
<i><%=image_tag "Machinery.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Valuable Jewelry, Gem & Metal'%>
<i><%=image_tag "ValuableJewelry.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Wholesaler/Distributor'%>
<i><%=image_tag "Businessservices.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Bags, Rubber & Plastics'%>
<i><%=image_tag "Bags.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Energy, Environments & Power'%>
<i><%=image_tag "Energy.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Exporter/Importer'%>
<i><%=image_tag "Businessservices.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Paper & Packing material'%>
<i><%=image_tag "Paper.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Printing, publishing & Hardware'%>
<i><%=image_tag "Printing.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Security, Alarm & Safety'%>
<i><%=image_tag "Security.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Laboratory & Measuring instruments'%>
<i><%=image_tag "Laboratory.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Pipes, Tubes & Fitting'%>
<i><%=image_tag "Pipes.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Handicrafts, Toys, Gifts & Crafts'%>
<i><%=image_tag "Toys.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Furniture & Furnishings'%>
<i><%=image_tag "Furniture.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Games, Movies & Entertainment'%>
<i><%=image_tag "Games.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%elsif @user.business_type == 'Business services & Freelancer'%>
<i><%=image_tag "Businessservices.png",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%else%>
<i><%=image_tag "",class: "img-responsive",:size => "60x40",style: "width:40%" %></i>
<%end%>
<h3 class=""><b><%=@user.fullname.first(20).capitalize%></b></h3>
<h4 class=""><%=@user.business_type%></h4>
<h5 class=""><%=@user.country.first(25).capitalize%></h5>
<h5 class=""><%=@user.email.first(30).capitalize%></h5>
<h5 class=""><%=@user.mobile_number.first(20).capitalize%></h5>
</div>
</div>


<div class="col-md-9 col-sm-9">
<div class="user_profile w3-panel w3-card w3-responsive">
<div class="w3-container w3-padding">
<h4 class="w3-text-teal"><b>Business Information</b></h4>
<%if @user.profiles.length == 0%>
<% if user_signed_in? %>
<% if current_user.id == @user.id%>
<h5 class=""><%=link_to"Add Business Information.",new_profile_path,class: "w3-teal w3-btn w3-border w3-hover-blue-grey"%></h5>
<p class="w3-text-red">Enhance your company's visibility by adding business information for better buyer understanding.</p>
<%end%>
<%end%>
<%end%>

<%@user.profiles.limit(1).each do |data| %>
<p><b>Product : </b><%=data.product_name%></p>
<p><b>Company : </b><%=data.company_name%></p>
<p><b>Minimun Order : </b><%=data.minimun_order%></p>
<p><b>Target Country : </b><%=data.target_country%></p>
<p><b>Company Info : </b><%=data.about_company%></p>
<% if current_user == data.user %>

<div class="d-flex align-items-center justify-content-start">
  <%= link_to "Edit",edit_profile_path(user_id: @user.id, profile_id: data.id), class: "w3-teal w3-btn mr-3"%>
  <%= button_to "Delete", profile_path(data), method: :delete,class: "w3-teal w3-btn", data: { confirm: 'Are you sure?' } %>
</div>
<%end%>
<%end%>
</div>
</div>
</div>

</div>
</div>


<% if user_signed_in? %>
<% if current_user.id == @user.id%>
<div class="col-md-12 col-sm-12 w3-light-grey">
<div class="w3-row">
<div class="w3-panel w3-card w3-responsive">
<h5 class="w3-text-teal"><b>Message sent as an Inquiry</b></h5>


<%if @user.connect_buyers.length == 0%>
<p class="">In Free Account: You Can Connect with Two Buyers</p>
<p><%=link_to"Connect Buyer",exportleads_path,class: "w3-btn w3-teal w3-button w3-border w3-hover-blue-grey"%></p>
<%elsif @user.connect_buyers.length >= 2%>
<p class="w3-text-red">Free Account:You Can Connect With Two Buyers. Unlock Unlimited Access.</p>
<p><%=link_to"Contact Us",new_home_path,class: "w3-btn w3-teal w3-button w3-border w3-hover-blue-grey"%></p>
<%end%>


<%@user.connect_buyers.limit(2).each do |buyer|%>
  <div class="col-md-4 col-sm-4">
    <div class="w3-panel w3-card w3-responsive">
      <div class="w3-container w3-padding">
        <p><%=buyer.name%></p>
        <p><%=buyer.email%></p>
        <p><%=buyer.country%></p>
        <p><%=buyer.Phone_number%></p>
        <p><%=buyer.product_detail%></p>
        <p><%=buyer.message%></p>
        <% if current_user == buyer.user %>
        <div class="d-flex align-items-center justify-content-start">
          <%= link_to "Edit", edit_connect_buyer_path(user_id: current_user.id, buyer_id: buyer.id), class: "w3-teal w3-btn mr-3"%>
          <%= button_to "Delete", connect_buyer_path(buyer), method: :delete, class: "w3-teal w3-btn", data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  </div>
  <%end%>
<%end%>
</div>
</div>
</div>
<%end%>
<%end%>

</div>





</body>
</html>