config/routes.rb
Rails.application.routes.draw do
devise_for :users
root "homes#index"
resources :exportnews
resources :photos
resources :homes
resources :vegetables
resources :profiles
resources :news
resources :exportleads
resources :connect_buyers
get '/trade_news' => 'exportleads#trade_news'
get '/export_leads' => 'exportleads#export_leads'
get '/home_password_974000' => 'homes#home_password_974000'
get '/about_us' => 'homes#about_us'
get '/privacy_policy' =>'homes#privacy_policy'  
get '/terms_and_condition' =>'homes#terms_and_condition'   
get '/barley' => 'homes#barley'
get '/buckwheat' =>'homes#buckwheat'    
get '/barley' => 'homes#barley'
get '/buckwheat' =>'homes#buckwheat'
get '/canary_seed' =>'homes#canary_seed'
get '/cotton' =>'homes#cotton'
get '/fonio' =>'homes#fonio'
get '/maize' =>'homes#maize'
get '/millet_crop' =>'homes#millet_crop'
get '/oats' => 'homes#oats'
get '/quinoa' => 'homes#quinoa'
get'/rice' => 'homes#rice'
get'/rye' => 'homes#rye'
get'/sorghum' => 'homes#sorghum'
get'/triticale' => 'homes#triticale'
get'/wheat' => 'homes#wheat'
get'/bitter_gourd' => 'vegetables#bitter_gourd'
get'/broccoli' => 'vegetables#broccoli'
get'/cabbages' => 'vegetables#cabbages'
get'/capsicums' => 'vegetables#capsicums'
get'/carrots' => 'vegetables#carrots'
get'/cassava' => 'vegetables#cassava'
get'/cauliflower' => 'vegetables#cauliflower'
get'/chickpea' => 'vegetables#chickpea'
get'/chicory' => 'vegetables#chicory'
get'/cucumber' => 'vegetables#cucumber'
get'/drumstick' => 'vegetables#drumstick'
get'/dry_bean' => 'vegetables#dry_bean'
get'/eggplant' => 'vegetables#eggplant'
get'/ginger' => 'vegetables#ginger'
get'/green_bean' => 'vegetables#green_bean'
get'/green_peas' => 'vegetables#green_peas'
get'/ladys_finger' => 'vegetables#ladys_finger'
get'/lentil' => 'vegetables#lentil'
get'/lettuce' => 'vegetables#lettuce'
get'/mushroom' => 'vegetables#mushroom'
get'/okra' => 'vegetables#okra'
get'/onion' => 'vegetables#onion'
get'/potato' => 'vegetables#potato'
get'/pulses' => 'vegetables#pulses'
get'/pumpkin_squash_gourd' => 'vegetables#pumpkin_squash_gourd'
get'/radish' => 'vegetables#radish'
get'/rapeseed_canola' => 'vegetables#rapeseed_canola'
get'/ridge_Gourd' => 'vegetables#ridge_Gourd'
get'/sunflower' => 'vegetables#sunflower'
get'/sesame' => 'vegetables#sesame'
get'/soybean' => 'vegetables#soybean'
get'/spinach' => 'vegetables#spinach'
get'/sugar_cane' => 'vegetables#sugar_cane'
get'/sugar_beet_beetroot' => 'vegetables#sugar_beet_beetroot'
get'/sunflower_seed' => 'vegetables#sunflower_seed'
get'/sanflower' => 'vegetables#sanflower'
get'/tomato' => 'vegetables#tomato'
get'/turnip' => 'vegetables#turnip'
get'/yams' =>'vegetables#yams' 
get '/apple' =>'fruits#apple'
get '/apricot' =>'fruits#apricot'
get '/avocado' =>'fruits#avocado'
get '/banana' =>'fruits#banana'
get '/black_currant' =>'fruits#black_currant'
get '/blackberry' =>'fruits#blackberry'
get '/blueberry' =>'fruits#blueberry'
get '/cherry' =>'fruits#cherry'
get '/coconut' =>'fruits#coconut'
get '/currant' =>'fruits#currant'
get '/custard_apple' =>'fruits#custard_apple'
get '/date' =>'fruits#date'
get '/dragon_fruit' =>'fruits#dragon_fruit'
get '/fig' =>'fruits#fig'
get '/gooseberry' =>'fruits#gooseberry'
get '/grape' =>'fruits#grape'
get '/guava' =>'fruits#guava'
get '/jackfruit' =>'fruits#jackfruit'
get '/kiwifruit' =>'fruits#kiwifruit'
get '/lemons' =>'fruits#lemons'
get '/mango' =>'fruits#mango'
get '/mangosteen' =>'fruits#mangosteen'
get '/muskmelon' =>'fruits#muskmelon'
get '/olive' =>'fruits#olive'
get '/oranges' =>'fruits#oranges'
get '/papaya' =>'fruits#papaya'
get '/passion_fruit' =>'fruits#passion_fruit'
get '/peach' =>'fruits#peach'
get '/pear' =>'fruits#pear'
get '/pineapple' =>'fruits#pineapple'
get '/plums' =>'fruits#plums'
get '/pomegranate' =>'fruits#pomegranate'
get '/quince' =>'fruits#quince'
get '/raspberry' =>'fruits#raspberry'
get '/strawberry' =>'fruits#strawberry'
get '/watermelon' =>'fruits#watermelon'
get '/beef' => 'meats#beef'
get '/buffalo' => 'meats#buffalo'
get '/camel' => 'meats#camel'
get '/chicken' => 'meats#chicken'
get '/duck' => 'meats#duck'
get '/goat' => 'meats#goat'
get '/goose' => 'meats#goose'
get '/guinea' => 'meats#guinea'
get '/horse' => 'meats#horse'
get '/pork' => 'meats#pork'
get '/rabbit' => 'meats#rabbit'
get '/sheep' => 'meats#sheep'
get '/turkey' => 'meats#turkey'

get '/beer' => 'milks#beer'
get '/buffalo_milk' => 'milks#buffalo_milk'
get '/camel_milk' => 'milks#camel_milk'
get '/coffee' => 'milks#coffee'
get '/cow_milk' => 'milks#cow_milk'
get '/goat_milk' => 'milks#goat_milk'
get '/milk' => 'milks#milk'
get '/sheep_milk' => 'milks#sheep_milk'
get '/tea' => 'milks#tea'
get '/wine' => 'milks#wine'
get '/almonds' => 'nuts#almonds'
get '/brazil_nuts' => 'nuts#brazil_nuts'
get '/cashews' => 'nuts#cashews'
get '/chestnuts' => 'nuts#chestnuts'
get '/filberts' => 'nuts#filberts'
get '/hazelnuts' => 'nuts#hazelnuts'
get '/macadamia_nuts' => 'nuts#macadamia_nuts'
get '/peanuts' => 'nuts#peanuts'
get '/pecans' => 'nuts#pecans'
get '/pine_nuts' => 'nuts#pine_nuts'
get '/pistachios' => 'nuts#pistachios'
get '/sheanut' => 'nuts#sheanut'
get '/walnuts' => 'nuts#walnuts'
get '/anise_star' => 'spices#anise_star'
get '/bay_leaves' => 'spices#bay_leaves'
get '/black_pepper' => 'spices#black_pepper'
get '/cardamom' => 'spices#cardamom'
get '/chili_pepper' => 'spices#chili_pepper'
get '/cinnamon' => 'spices#cinnamon'
get '/cloves' => 'spices#cloves'
get '/coriander' => 'spices#coriander'
get '/cumin' => 'spices#cumin'
get '/fennel' => 'spices#fennel'
get '/fenugreek' => 'spices#fenugreek'
get '/ginger' => 'spices#ginger'
get '/mace' => 'spices#mace'
get '/mustard_seeds' => 'spices#mustard_seeds'
get '/nutmeg' => 'spices#nutmeg'
get '/oregano' => 'spices#oregano'
get '/paprika' => 'spices#paprika'
get '/peppermint' => 'spices#peppermint'
get '/rosemary' => 'spices#rosemary'
get '/saffron' => 'spices#saffron'
get '/thyme' => 'spices#thyme'
get '/turmeric' => 'spices#turmeric'
get '/vanilla' => 'spices#vanilla' 

get '/cheese' => 'milks#cheese' 
get '/cocoa' => 'milks#cocoa'	
get '/yerba_mate' => 'milks#yerba_mate'	
get '/egg' => 'milks#egg'
get '/honey' => 'milks#honey'
get '/olive_oil' => 'milks#olive_oil'	 
get '/tobacco' => 'milks#tobacco'	 

get '/fiber' => 'fiber#fiber'
get '/abaca_fiber' => 'fiber#abaca_fiber'	
get '/agave_fiber' => 'fiber#agave_fiber'	
get '/bast_fiber' => 'fiber#bast_fiber'	
get '/flax_fiber' => 'fiber#flax_fiber'	
get '/jute_fiber' => 'fiber#jute_fiber'	
get '/kapok_fiber' => 'fiber#kapok_fiber'		
get '/ramie_fiber' => 'fiber#ramie_fiber'	
get '/rubber_fiber' => 'fiber#rubber_fiber'	
get '/silk_fiber' => 'fiber#silk_fiber'	
get '/sisal_fiber' => 'fiber#sisal_fiber' 

get '/wool' => 'fiber#wool' 

get '/fish' => 'seafoods#fish'
get '/Oyster' => 'seafoods#Oyster'
get '/seaweed' => 'seafoods#seaweed'
get '/caviar' => 'seafoods#caviar'
get '/crab' => 'seafoods#crab'
get '/lobsters' => 'seafoods#lobsters'
get '/clam' => 'seafoods#clam'
get '/oyster' => 'seafoods#oyster'
get '/octopus' => 'seafoods#octopus'
get '/squid' => 'seafoods#squid'
get '/shrimps' => 'seafoods#shrimps'

end

app/models/exportlead.rb
class Exportlead < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_by_keyword, against: [:wanted, :buyer, :title, :contact, :date, :review], using: {
    tsearch: { prefix: true }
  }

  def self.search_results(search_query, params)
    if search_query.present?
      search_by_keyword(search_query).page(params[:page]).per(20)
    else
      all.page(params[:page]).per(20)
    end
  end

  def self.search(search)
    if search
      self.where("LOWER(wanted) LIKE ?", "%#{search.downcase}%")
    else
      self.all
    end
  end

end

app/controllers/exportleads_controller.rb
class ExportleadsController < ApplicationController
    def index
        if params[:reset].present?
            params[:q] = nil
        end  
        @exportleads = Exportlead.order("random()").search_results(params[:q], params)
        @exportnews = Exportnew.order("random()").search_results(params[:q], params)
        @connect_buyer = ConnectBuyer.new
        end
    def new

    end
    def trade_news
        @exportnew = Exportnew.order("random()").search(params[:search])
        @news, @exportnew = pagy(@exportnew)
    end  

    def export_leads
        @connect_buyer = ConnectBuyer.new
        @exportlead = Exportlead.order("random()").search(params[:search])
        @leads, @exportlead = pagy(@exportlead)
    end

end

app/helpers/exportleads_helper.rb
module ExportleadsHelper
end

app/views/exportleads/export_leads.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Eximsquare</title>
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
.ada {
      font-size:26px;
      color: green;
      }
.aba {
      color: green;
     }
.pagy-nav.pagination {
  display: inline-block;
}

.page a, .page.gap {
  color: black;
  padding: 6px 8px;
  text-decoration: none;
  transition: background-color .3s;
  border: 1px solid #ddd; 
}

.page.active {
  background-color: #4d636f;
  color: white;
  padding: 6px 8px;
}
</style>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7201484819730179"
     crossorigin="anonymous"></script>

</head>
<body>
<div class="w3-hide-large w3-hide-medium w3-container w3-content" style="max-width:1400px;margin-top:80px"> 
<div class="row">
<div class="col-sm-10 col-md-10">
<div class="w3-container w3-padding">
<%=form_tag export_leads_path, :method => 'get' do %>
<%= text_field_tag :search, params[:search], :size=>"20", placeholder: "Search Product Leads",class: "form-control" %>
<%= submit_tag "Search", :wanted => nil,class: "btn w3-teal" %>
<% end %>
</div>
</div>
</div>

<div class="col-sm-10 col-md-10">
  <div class="w3-row w3-white">
    <div class="w3-col m12">
      <%@exportlead.each do |exportnew|%>
        <div class="w3-card w3-round w3-light-grey">
          <div class="w3-container w3-padding">
            <h6 class=""><b><%=exportnew.wanted.titleize%></b></h6>
              <p class=""><b><%=exportnew.buyer.capitalize%></b></p>
              </br>
              <p class=""><%=exportnew.title.capitalize%></p>
              <p class=""><%=exportnew.contact%></p>
              <% if user_signed_in? %> 
             <button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-btn w3-teal w3-hover-blue-grey" title="EximSquare" type="button" class="w3-btn w3-teal w3-theme-d1 w3-margin-bottom"><i class="fa fa-handshake-o">&nbsp;&nbsp;</i>Connect Buyer</button>
             <% elsif !user_signed_in? %>
             <p><%=link_to"Connect Buyer",new_user_session_path,class: "w3-btn w3-teal w3-border w3-hover-blue-grey"%></p>
             <%end%> 
  <div id="id01" class="w3-modal">
  <div class="w3-modal-content w3-card-4 w3-animate-top">
    <header class="w3-container w3-teal w3-display-container"> 
      <span onclick="document.getElementById('id01').style.display='none'" class="w3-button w3-teal w3-display-topright"><i class="fa fa-remove"></i></span>
      <h5>Sending Inquiry For: Buyer</h5>
    </header>
    </br>
    <div class="w3-container">
<%= form_for @connect_buyer do |f| %>

<%= f.label :name,'Your Name'%></br>
<%= f.text_field :name,class: "form-control",:maxlength=>"50",placeholder:"Name can't be blank"%></br>

<%= f.label :email,'Email'%></br>
<%= f.text_field :email,class: "form-control",:maxlength=>"50",placeholder:"Email can't be blank"%></br>

<%= f.label :country,'Country'%></br>
<%= f.text_field :country,class: "form-control",:maxlength=>"60",placeholder:"Country name can't be blank"%></br>

<%= f.label :Phone_number,'Phone Num with Country Code'%></br>
<%= f.text_field :Phone_number,class: "form-control",:maxlength=>"40",placeholder:"Phone Num can't be blank"%></br>

<%= f.label :product_detail,'Your Product Detail'%></br>
<%= f.text_field :product_detail,class: "form-control",:maxlength=>"60",placeholder:"Product Detail can't be blank"%></br>

<%= f.label :message,'Message'%></br>
<%= f.text_area :message,class: "form-control",:maxlength=>"500",:rows => 4,:cols => 60,placeholder:"Message can't be blank"%></br>

<%= f.submit"Connect Buyer",class: "w3-btn w3-teal"%>

<%end%>
    </div>
    </br>
    <footer class="w3-container w3-teal">
      <p class="text-center">Eximsquare</p>
    </footer>
    
  </div>
</div>

<span class="w3-right"><%=rand(35.day.ago..0.day.from_now).to_date%></span>
              <div class="w3-col m12"></br>
              <p class="w3-left w3-green"><%=["Lead : Verified",""].sample%></p>
              <span class="w3-right aba">Review : <sub class="ada"><%=["* * *","* * * *","* * * * *"].sample%><sub></span>
              </div>
          </div>
         </div>
         </br>
      <%end%>
    </div>  
  </div>
<div class="w3-center"><%== pagy_nav(@leads)%></div>
</div>
    

</div>
</div>


 


</body>
</html> 